name: CI

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps: 
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro
      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          python -m unittest tests/test_model.py
      
      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python scripts/promote_model.py

      # - name: Run Flask app tests
      #   if: success()
      #   env:
      #     DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      #   run: python -m unittest tests/test_flask_app.py
    
      - name: Login to Docker hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DAGS_HUB_USERNAME}}
          password: ${{secrets.DAGS_HUB_ACCESS_TOKEN}}
      
      - name: Build Docker Image
        if: success()
        run: |
          docker build -t ${{secrets.DAGS_HUB_USERNAME}}/sentiment_analysis:v2 .

      - name: Push Docker image to Docker hub
        if: success()
        run: |
          docker push ${{secrets.DAGS_HUB_USERNAME}}/sentiment_analysis:v2
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          scripts: |
            docker pull ${{secrets.DAGS_HUB_USERNAME}}/sentiment_analysis:v2
            docker stop my-app || true
            docker rm my-app || true
            docker run -p 80:5000 --name my-app -e DAGSHUB_PAT=ae1da4affb727c1edc1942e3c27d6c84ee917997 ${{secrets.DAGS_HUB_USERNAME}}/sentiment_analysis:v2



    
